const list = [
  {
    index: 0,
    img: require('@/assets/img/renwuxiadabull.png'),
    imgWhite: require('@/assets/img/renwuxiada.png'),
    name: '任务下达',
    myRouter: 'entrustlist'
  }, {
    index: 1,
    img: require('@/assets/img/renwu-3.png'),
    // imgWhite: require('@/assets/img/renwuxiada-2.png'),
    name: '我的任务',
    myRouter: ''
  }, {
    index: 2,
    img: require('@/assets/img/weibiaoti--.png'),
    imgWhite: require('@/assets/img/weibiaoti_white.png'),
    name: '任务草稿',
    myRouter: 'entrustdraft'
  }, {
    index: 3,
    img: require('@/assets/img/fenpei-2.png'),
    imgWhite: require('@/assets/img/ren_wu_fen_pei_white.png'),
    name: '任务分配',
    myRouter: 'taskallot'
  }, {
    index: 4,
    img: require('@/assets/img/bianji-5.png'),
    imgWhite: require('@/assets/img/bianji-51_white.png'),
    name: '报告编辑',
    myRouter: 'surveyredact'
  }, {
    index: 5,
    img: require('@/assets/img/baogao.png'),
    imgWhite: require('@/assets/img/baogao_white.png'),
    name: '我的报告',
    myRouter: 'report'
  }, {
    index: 6,
    img: require('@/assets/img/xiaoyanliebiao.png'),
    imgWhite: require('@/assets/img/xiaoyanliebiao1_white.png'),
    name: '报告校验',
    myRouter: 'surveyparity'
  }, {
    index: 7,
    img: require('@/assets/img/shenhe-2.png'),
    imgWhite: require('@/assets/img/shenhe-2_white.png'),
    name: '报告审核',
    myRouter: 'surveyaudit'
  }, {
    index: 8,
    img: require('@/assets/img/pizhun-3.png'),
    imgWhite: require('@/assets/img/pizhun-3_white.png'),
    name: '报告批准',
    myRouter: 'surveyratify'
  }, {
    index: 9,
    img: require('@/assets/img/bao_gao_chu_jiao.png'),
    imgWhite: require('@/assets/img/bao_gao_chu_jiao_white.png'),
    name: '报告初校',
    myRouter: 'surveyverify'
  }, {
    index: 10,
    img: require('@/assets/img/ren_wu_guan_li.png'),
    imgWhite: require('@/assets/img/ren_wu_guan_li(1)_white.png'),
    name: '任务管理',
    myRouter: 'taskmanage'
  }, {
    index: 11,
    img: require('@/assets/img/wen_ti_bao_gao.png'),
    imgWhite: require('@/assets/img/wen_ti_bao_gao_white.png'),
    name: '问题报告',
    myRouter: 'surveyissue'
  }, {
    index: 12,
    img: require('@/assets/img/bao_gao_gui_dang.png'),
    imgWhite: require('@/assets/img/bao_gao_gui_dang_white.png'),
    name: '报告归档',
    myRouter: 'pigeonhole'
  }, {
    index: 13,
    img: require('@/assets/img/xiu_gai_dan_GL.png'),
    imgWhite: require('@/assets/img/xiu_gai_dan_GL_white.png'),
    name: '修改单管理',
    myRouter: 'entrustamend'
  }
];
export default list;
